CREATE TABLE IF NOT EXISTS MY_ORDER (
  ORDER_ID varchar(100) PRIMARY KEY NOT NULL,
  BEGIN_TIME bigint NOT NULL,
  END_TIME bigint NOT NULL,
  PAYLOAD varchar(1000)
);

CREATE TABLE IF NOT EXISTS MY_STEP (
  ORDER_ID varchar(100) REFERENCES MY_ORDER NOT NULL,
  PHASE varchar(20) NOT NULL,
  BEGIN_TIME bigint NOT NULL,
  END_TIME bigint NOT NULL,
  IS_CURRENT BOOLEAN NOT NULL
);
