version: '3.1'

services:
    orderserver:
        image: orderserver:dev
        networks:
            - order-net   
        links:
            - rabbitmq
            - db
        restart: always
        environment:
            RABBIT_HOST: 192.168.3.80
            POSTGRE_HOST: 192.168.3.80
            RABBIT_CONSUMERS: 5
            RABBIT_MAXCONSUMERS: 10 

    restserver:
        image: restserver:dev
        networks:
            - order-net   
        links:
            - rabbitmq
            - db
        restart: always
        environment:
            RABBIT_HOST: 192.168.3.80
            POSTGRE_HOST: 192.168.3.80       
        ports:
            - 9090:9090
            - 9091:9091

    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbit
        networks:
            - order-net   
        restart: always
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"

    db:
        image: postgres
        networks:
            - order-net   
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db
        ports:
            - "5432:5432"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

networks:
    order-net:
        driver: bridge        

